// flow-typed signature: cbb6043f43e54573400b2aa47241a74f
// flow-typed version: <<STUB>>/graphql-config_v^2.2.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-config/lib/__tests__/basic/findGraphQLConfigFile' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/__tests__/basic/getGraphQLConfig' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/__tests__/basic/getGraphQLProjectConfig' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/__tests__/endpoint-extension/resolve' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/__tests__/endpoint-extension/string-refs' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/__tests__/introspection-query/getSchema' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/__tests__/utils' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/__tests__/yaml/test' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/errors' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/extensions/endpoints/EndpointsExtension' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/extensions/endpoints' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/extensions/endpoints/resolveRefString' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/extensions' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/findGraphQLConfigFile' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/getGraphQLConfig' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/GraphQLConfig' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/GraphQLProjectConfig' {
  declare module.exports: any;
}

declare module 'graphql-config/lib' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/types' {
  declare module.exports: any;
}

declare module 'graphql-config/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-config/lib/__tests__/basic/findGraphQLConfigFile.js' {
  declare module.exports: $Exports<'graphql-config/lib/__tests__/basic/findGraphQLConfigFile'>;
}
declare module 'graphql-config/lib/__tests__/basic/getGraphQLConfig.js' {
  declare module.exports: $Exports<'graphql-config/lib/__tests__/basic/getGraphQLConfig'>;
}
declare module 'graphql-config/lib/__tests__/basic/getGraphQLProjectConfig.js' {
  declare module.exports: $Exports<'graphql-config/lib/__tests__/basic/getGraphQLProjectConfig'>;
}
declare module 'graphql-config/lib/__tests__/endpoint-extension/resolve.js' {
  declare module.exports: $Exports<'graphql-config/lib/__tests__/endpoint-extension/resolve'>;
}
declare module 'graphql-config/lib/__tests__/endpoint-extension/string-refs.js' {
  declare module.exports: $Exports<'graphql-config/lib/__tests__/endpoint-extension/string-refs'>;
}
declare module 'graphql-config/lib/__tests__/introspection-query/getSchema.js' {
  declare module.exports: $Exports<'graphql-config/lib/__tests__/introspection-query/getSchema'>;
}
declare module 'graphql-config/lib/__tests__/utils.js' {
  declare module.exports: $Exports<'graphql-config/lib/__tests__/utils'>;
}
declare module 'graphql-config/lib/__tests__/yaml/test.js' {
  declare module.exports: $Exports<'graphql-config/lib/__tests__/yaml/test'>;
}
declare module 'graphql-config/lib/errors.js' {
  declare module.exports: $Exports<'graphql-config/lib/errors'>;
}
declare module 'graphql-config/lib/extensions/endpoints/EndpointsExtension.js' {
  declare module.exports: $Exports<'graphql-config/lib/extensions/endpoints/EndpointsExtension'>;
}
declare module 'graphql-config/lib/extensions/endpoints/index' {
  declare module.exports: $Exports<'graphql-config/lib/extensions/endpoints'>;
}
declare module 'graphql-config/lib/extensions/endpoints/index.js' {
  declare module.exports: $Exports<'graphql-config/lib/extensions/endpoints'>;
}
declare module 'graphql-config/lib/extensions/endpoints/resolveRefString.js' {
  declare module.exports: $Exports<'graphql-config/lib/extensions/endpoints/resolveRefString'>;
}
declare module 'graphql-config/lib/extensions/index' {
  declare module.exports: $Exports<'graphql-config/lib/extensions'>;
}
declare module 'graphql-config/lib/extensions/index.js' {
  declare module.exports: $Exports<'graphql-config/lib/extensions'>;
}
declare module 'graphql-config/lib/findGraphQLConfigFile.js' {
  declare module.exports: $Exports<'graphql-config/lib/findGraphQLConfigFile'>;
}
declare module 'graphql-config/lib/getGraphQLConfig.js' {
  declare module.exports: $Exports<'graphql-config/lib/getGraphQLConfig'>;
}
declare module 'graphql-config/lib/GraphQLConfig.js' {
  declare module.exports: $Exports<'graphql-config/lib/GraphQLConfig'>;
}
declare module 'graphql-config/lib/GraphQLProjectConfig.js' {
  declare module.exports: $Exports<'graphql-config/lib/GraphQLProjectConfig'>;
}
declare module 'graphql-config/lib/index' {
  declare module.exports: $Exports<'graphql-config/lib'>;
}
declare module 'graphql-config/lib/index.js' {
  declare module.exports: $Exports<'graphql-config/lib'>;
}
declare module 'graphql-config/lib/types.js' {
  declare module.exports: $Exports<'graphql-config/lib/types'>;
}
declare module 'graphql-config/lib/utils.js' {
  declare module.exports: $Exports<'graphql-config/lib/utils'>;
}
