// flow-typed signature: 0f7cb75e9bd651ce75c3814b4893e1ce
// flow-typed version: <<STUB>>/lodash.flatmap_v^4.5.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.flatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.flatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.flatmap/index' {
  declare module.exports: $Exports<'lodash.flatmap'>;
}
declare module 'lodash.flatmap/index.js' {
  declare module.exports: $Exports<'lodash.flatmap'>;
}
